[package]
name = "keyboard_optimizer_layoutgen"
version = "3000.0.0"
authors = ["Ilion Iasoon Beyst"]

[dependencies]
rand = "*"
error-chain = "*"
byteorder = "1"

serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0"

[profile.release]
debug = true
